### ISSUE TITLE
Demo ipynb evaluation result inconsistent

### ISSUE THREAD

**Issue by j-min** [Yinan-Zhao/vizwiz-caption#5]
Hi,

I cloned the repo and ran the notebook without modifying the code.
I got inconsistent results from the original notebook. Could you please confirm that the current results in the notebook are reproducible?

Below is my log from `vizwizEval.evaluate()`

```
tokenization...
setting up scorers...
computing Bleu score...
{'testlen': 86410, 'reflen': 83011, 'guess': [86410, 78868, 71335, 63802], 'correct': [31457, 12531, 8925, 7741]}
ratio: 1.0409463806001489
Bleu_1: 0.364
Bleu_2: 0.241
Bleu_3: 0.193
Bleu_4: 0.172
computing Rouge score...
ROUGE_L: 0.289
computing CIDEr score...
CIDEr: 0.318
computing SPICE score...
SPICE: 0.060
computing METEOR score...
METEOR: 0.120
```

My result screenshot:
![image](https://user-images.githubusercontent.com/18069263/128652987-920014c3-768b-47ec-8aa1-77ffd5e09d16.png)

Screenshot of current notebook file in this github:
![image](https://user-images.githubusercontent.com/18069263/128652932-bcfd7765-ff7f-46fe-80a1-10365d72e777.png)

My environment: Ubuntu 20.04 / python 3.8 / java 1.8.0

**Comment by j-min** [comment]
I found there's a note in the [captioning task website](https://vizwiz.org/tasks-and-datasets/image-captioning/) as below. Maybe this is due to the annotation file update? I guess I'm using the recent one but the last commit on this repo is before April 2020.

`Note: If you downloaded the annotation file before April 17, 2020 that version contained a special character ‘\r’ which can cause caption misalignment when tokenizing each caption. If you have that older vision, please make sure you either download the current annotation file or remove ‘\r’ from all captions.`

**Comment by Yinan-Zhao** [comment]
Thanks for letting me know. It is because the annotation file has been updated. I just updated the demo results with the current version of the annotation.
